import { User, Artist, MusicTrack } from './types';

export const mockUsers: Record<string, User & { password: string }> = {
  admin: {
    id: 'user-admin-1',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'super_admin',
    password: 'password123',
    profile: {
      first_name: 'Admin',
      last_name: 'User',
      email: 'admin@example.com',
    },
  },
  manager: {
    id: 'user-manager-1',
    email: 'manager@example.com',
    name: 'Alex Manager',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Alex',
      last_name: 'Manager',
      email: 'manager@example.com',
    },
  },
  artist1: {
    id: 'user-artist-1',
    email: 'artist1@example.com',
    name: 'Sarah Chen',
    role: 'artist',
    password: 'password123',
    profile: {
      first_name: 'Sarah',
      last_name: 'Chen',
      email: 'artist1@example.com',
      dateOfBirth: '1995-03-15',
      gender: 'female',
      address: '123 Music Lane, Nashville, TN',
      firstReleaseYear: 2018,
      numberOfAlbums: 3,
    },
  },
  artist2: {
    id: 'user-artist-2',
    email: 'artist2@example.com',
    name: 'Jordan Miles',
    role: 'artist',
    password: 'password123',
    profile: {
      first_name: 'Jordan',
      last_name: 'Miles',
      email: 'artist2@example.com',
      dateOfBirth: '1992-07-22',
      gender: 'male',
      address: '456 Artist Ave, Los Angeles, CA',
      firstReleaseYear: 2015,
      numberOfAlbums: 5,
    },
  },
};

export const mockArtists: Artist[] = [
  {
    id: 'artist-1',
    email: 'sarah.music@example.com',
    displayName: 'Sarah Chen',
    firstReleaseYear: 2018,
    albumsReleased: 3,
    status: 'active',
    createdAt: '2024-01-15',
    managerId: 'user-manager-1',
    managerName: 'Alex Manager',
  },
  {
    id: 'artist-2',
    email: 'jordan.beats@example.com',
    displayName: 'Jordan Miles',
    firstReleaseYear: 2015,
    albumsReleased: 5,
    status: 'active',
    createdAt: '2023-11-20',
    managerId: 'user-manager-1',
    managerName: 'Alex Manager',
  },
  {
    id: 'artist-3',
    email: 'maya.sound@example.com',
    displayName: 'Maya Patel',
    firstReleaseYear: 2020,
    albumsReleased: 2,
    status: 'active',
    createdAt: '2024-02-03',
    managerId: 'user-manager-2',
    managerName: 'Blake Robertson',
  },
  {
    id: 'artist-4',
    email: 'carlos.rhythm@example.com',
    displayName: 'Carlos Rodriguez',
    firstReleaseYear: 2019,
    albumsReleased: 4,
    status: 'pending',
    createdAt: '2024-02-10',
    managerId: 'user-manager-3',
    managerName: 'Casey Johnson',
  },
  {
    id: 'artist-5',
    email: 'emma.tunes@example.com',
    displayName: 'Emma Wilson',
    firstReleaseYear: 2021,
    albumsReleased: 1,
    status: 'active',
    createdAt: '2024-02-05',
    managerId: 'user-manager-2',
    managerName: 'Blake Robertson',
  },
  {
    id: 'artist-6',
    email: 'david.waves@example.com',
    displayName: 'David Kim',
    firstReleaseYear: 2017,
    albumsReleased: 6,
    status: 'active',
    createdAt: '2024-01-08',
    managerId: 'user-manager-4',
    managerName: 'Dana Lee',
  },
  {
    id: 'artist-7',
    email: 'lucia.melodies@example.com',
    displayName: 'Lucia Rossi',
    firstReleaseYear: 2022,
    albumsReleased: 1,
    status: 'pending',
    createdAt: '2024-02-12',
    managerId: 'user-manager-3',
    managerName: 'Casey Johnson',
  },
  {
    id: 'artist-8',
    email: 'james.notes@example.com',
    displayName: 'James Turner',
    firstReleaseYear: 2018,
    albumsReleased: 3,
    status: 'active',
    createdAt: '2024-01-25',
    managerId: 'user-manager-5',
    managerName: 'Eric Martinez',
  },
  {
    id: 'artist-9',
    email: 'sophie.harmony@example.com',
    displayName: 'Sophie Laurent',
    firstReleaseYear: 2020,
    albumsReleased: 2,
    status: 'inactive',
    createdAt: '2024-01-10',
    managerId: 'user-manager-6',
    managerName: 'Fiona Brown',
  },
  {
    id: 'artist-10',
    email: 'marcus.groove@example.com',
    displayName: 'Marcus Johnson',
    firstReleaseYear: 2016,
    albumsReleased: 7,
    status: 'active',
    createdAt: '2023-12-15',
    managerId: 'user-manager-4',
    managerName: 'Dana Lee',
  },
];

export const mockTracks: MusicTrack[] = [
  {
    id: 'track-1',
    title: 'Midnight Dreams',
    album: 'Neon Nights',
    genre: 'Synthwave',
    createdAt: '2024-01-10',
    artistId: 'user-artist-1',
  },
  {
    id: 'track-2',
    title: 'Electric Pulse',
    album: 'Neon Nights',
    genre: 'Electronic',
    createdAt: '2024-01-12',
    artistId: 'user-artist-1',
  },
  {
    id: 'track-3',
    title: 'Urban Jungle',
    album: 'City Vibes',
    genre: 'Hip-Hop',
    createdAt: '2024-01-15',
    artistId: 'user-artist-1',
  },
  {
    id: 'track-4',
    title: 'Cosmic Journey',
    album: 'Space Odyssey',
    genre: 'Ambient',
    createdAt: '2023-12-20',
    artistId: 'user-artist-2',
  },
  {
    id: 'track-5',
    title: 'Desert Wind',
    album: 'Space Odyssey',
    genre: 'Ambient',
    createdAt: '2023-12-25',
    artistId: 'user-artist-2',
  },
];

export const mockManagers: (User & { password: string })[] = [
  {
    id: 'user-manager-1',
    email: 'manager@example.com',
    name: 'Alex Manager',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Alex',
      last_name: 'Manager',
      email: 'manager@example.com',
    },
  },
  {
    id: 'user-manager-2',
    email: 'manager2@example.com',
    name: 'Blake Robertson',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Blake',
      last_name: 'Robertson',
      email: 'manager2@example.com',
    },
  },
  {
    id: 'user-manager-3',
    email: 'manager3@example.com',
    name: 'Casey Johnson',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Casey',
      last_name: 'Johnson',
      email: 'manager3@example.com',
    },
  },
  {
    id: 'user-manager-4',
    email: 'manager4@example.com',
    name: 'Dana Lee',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Dana',
      last_name: 'Lee',
      email: 'manager4@example.com',
    },
  },
  {
    id: 'user-manager-5',
    email: 'manager5@example.com',
    name: 'Eric Martinez',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Eric',
      last_name: 'Martinez',
      email: 'manager5@example.com',
    },
  },
  {
    id: 'user-manager-6',
    email: 'manager6@example.com',
    name: 'Fiona Brown',
    role: 'artist_manager',
    password: 'password123',
    profile: {
      first_name: 'Fiona',
      last_name: 'Brown',
      email: 'manager6@example.com',
    },
  },
];
